parameters:
  settings:
    question_nums: 15
    tag_nums: 20
  vega.list.pagesize: 15
  vega.tag.nums: 20

twig:
  globals:
    sitename: 'Vega Question Answer System'
    siteurl: 'http://Vega.red'
    site_admin_email: 'heavenwoo@livve.com'